clinica2024/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core import views

from django.urls import path

from core import views

from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('relatorios/pacientes', views.PacientesListView.as_view(), name='relat_pacientes'),
    path('relatorios/pdfpacientes', views.RelatPdfPacientes.as_view(), name='pdf_pacientes'),

    path('relatorios/pacientes_por_convenio', views.PacientesConvenioListView.as_view(),
         name='pacientesporconvenio'),
    path('relatorios/pdfpacientes_por_convenio', views.RelatPdfPacientesPorConvenio.as_view(),
         name='RelatPdfPacientesPorConvenio'),

    path('relatorios/consulta_por_especialidade', views.ConsultaPorEspecialidadeListView.as_view(),
         name='consulta_por_especialidade'),
    path('relatorios/pdfconsulta_por_especialidade', views.RelatpdfConsultaPorEspecialidade.as_view(),
         name='pdfconsulta_por_especialidade'),

    path("relatorios/atendimento_por_especialidade", views.AtendimentoEspecialidadeListView.as_view(),
        name="relat_atendimento_por_especialidade"),
        path("relatorios/pdf/pdfatendimento_por_especialidade", views.RelatPdfAtendimentoEspecialidadeListView.as_view(),
        name="pdfatendimento_por_especialidade"),

]

core/models.py
from django.db import models


class Ambulatorio(models.Model):
    nome = models.CharField(max_length=200, blank=True, null=True)
    numleitos = models.IntegerField(blank=True, null=True)
    andar = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ambulatorio'
        verbose_name = 'Ambulatório'
        verbose_name_plural = 'Ambulatórios'

    def __str__(self):
        return self.nome


class Atende(models.Model):
    medico = models.ForeignKey('Medico', models.DO_NOTHING, db_column='medico', primary_key=True)  # The composite primary key (medico, convenio) found, that is not supported. The first column is selected.
    convenio = models.ForeignKey('Convenio', models.DO_NOTHING, db_column='convenio')

    class Meta:
        managed = False
        db_table = 'atende'
        unique_together = (('medico', 'convenio'),)
        verbose_name = 'Médico Convênio'
        verbose_name_plural = 'Médico Convênios'

    def __str__(self):
        return (f'Dr. {self.medico.nome} atende '
                f'convênio {self.convenio.nome}')


class Consulta(models.Model):
    data = models.DateField(blank=True, null=True)
    horario = models.TimeField(blank=True, null=True)
    medico = models.ForeignKey('Medico', models.DO_NOTHING, db_column='medico', blank=True, null=True)
    paciente = models.ForeignKey('Paciente', models.DO_NOTHING, db_column='paciente', blank=True, null=True)
    convenio = models.ForeignKey('Convenio', models.DO_NOTHING, db_column='convenio', blank=True, null=True)
    porcent = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'consulta'
        verbose_name = 'Consulta'
        verbose_name_plural = 'Consultas'

    def __str__(self):
        return (f'Consulta {self.paciente.nome} '
                f'com Dr. {self.medico.nome}')


class Convenio(models.Model):
    codconv = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'convenio'
        verbose_name = 'Convênio'
        verbose_name_plural = 'Convênios'

    def __str__(self):
        return self.nome


class Medico(models.Model):
    crm = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=200, blank=True, null=True)
    especialidade = models.CharField(max_length=100, blank=True, null=True)
    endereco = models.CharField(max_length=250, blank=True, null=True)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    idade = models.IntegerField(blank=True, null=True)
    salario = models.DecimalField(max_digits=12, decimal_places=2, blank=True, null=True)
    ambulatorio = models.ForeignKey(Ambulatorio, models.DO_NOTHING, db_column='idamb', blank=True, null=True)
    convenios = models.ManyToManyField('Convenio', through='Atende', verbose_name='convenios_medico')

    class Meta:
        managed = False
        db_table = 'medico'
        verbose_name = 'Médico'
        verbose_name_plural = 'Médicos'

    def __str__(self):
        return self.nome


class Paciente(models.Model):
    nome = models.CharField(max_length=200)
    endereco = models.CharField(max_length=250, blank=True, null=True)
    telefone = models.CharField(max_length=15, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    idade = models.IntegerField(blank=True, null=True)
    ambulatorio = models.ForeignKey(Ambulatorio, models.DO_NOTHING, db_column='idamb', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'paciente'
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def __str__(self):
        return self.nome


class Possui(models.Model):
    paciente = models.OneToOneField(Paciente, models.DO_NOTHING, db_column='paciente', primary_key=True)  # The composite primary key (paciente, convenio) found, that is not supported. The first column is selected.
    convenio = models.ForeignKey(Convenio, models.DO_NOTHING, db_column='convenio')
    tipo = models.CharField(max_length=1, blank=True, null=True)
    vencimento = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'possui'
        unique_together = (('paciente', 'convenio'),)
        verbose_name = 'Paciente x Convênio'
        verbose_name_plural = 'Paciente x Convênios'

    def __str__(self):
        return (f'{self.paciente.nome}, '
                f'convênio {self.convenio.nome}')

core/views.py
from io import BytesIO

from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.views import View
from django.views.generic import TemplateView, ListView
from xhtml2pdf import pisa
from django.db.models import Count
from django.db.models.functions import *
from django.db.models import Count, F
from django.template.loader import render_to_string

from core import models
from core.models import Paciente, Convenio, Consulta, Medico


class HomeTemplateView(TemplateView):
    template_name = "index.html"


class PacientesListView(ListView):
    template_name = "relatorios/pacientes.html"
    model = Paciente
    context_object_name = 'pacientes'


class RelatPdfPacientes(View):

    def get(self, request):
        pacientes = Paciente.objects.all()
        data = {
            'pacientes': pacientes,
        }
        template = get_template("relatorios/pdfpacientes.html")
        html = template.render(data)
        result = BytesIO()
        try:
            pdf = pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
            return HttpResponse(result.getvalue(),
                                content_type='application/pdf')
        except Exception as e:
            print(e)
            return None


class PacientesConvenioListView(ListView):
    template_name = 'relatorios/pacientes_por_convenio.html'
    model = Convenio
    context_object_name = 'convenios'

    def get_queryset(self):
        convenios = Convenio.objects.all()
        for convenio in convenios:
            pacientes = Paciente.objects.filter(possui__convenio=convenio)
            convenio.pacientes = pacientes
        return PacientesConvenioListView


class RelatPdfPacientesPorConvenio(View):

    def get(self, request):
        convenios = Convenio.objects.all()
        for convenio in convenios:
            pacientes = Paciente.objects.filter(possui__convenio=convenio)
            convenio.pacientes = pacientes

        data = {
            'convenios': convenios,
            'pacientes': pacientes,
        }

        template = get_template("relatorios/pdfpacientes_por_convenio.html")
        html = template.render(data)
        response = HttpResponse(content_type='application/pdf')

        result = BytesIO()
        try:
            pdf = pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
            response.write(result.getvalue())
            return response
        except Exception as e:
            print(e)
            return response


class ConsultaPorEspecialidadeListView(ListView):
    template_name = "relatorios/consulta_por_especialidade.html"
    model = Consulta
    context_object_name = 'Consulta por especialidade'
    queryset = Convenio.objects.all()


class RelatpdfConsultaPorEspecialidade(View):

    def get(self, request):
        consulta = Consulta.objects.all()
        data = {
            'Consulta': Consulta,
        }
        template = get_template("relatorios/pdfconsulta_por_especialidade.html")
        html = template.render(data)
        result = BytesIO()
        try:
            pisa.pisaDocument(BytesIO(html.encode('UTF-8')), result)
            return HttpResponse(result.getvalue(), content_type='application/pdf')
        except Exception as e:
            print(e)
            return RelatpdfConsultaPorEspecialidade


class AtendimentoEspecialidadeListView(ListView):
    template_name = 'relatorios/atendimento_por_especialidade.html'
    context_object_name = 'atendimento_por_especialidade'

    def get_queryset(self):
        especialidades = Medico.objects.values_list('especialidade', flat=True).distinct()

        atendimentos_por_especialidade = []
        print(especialidades)
        for especialidade in especialidades:
            atendimentos = Consulta.objects.filter(medico__especialidade=especialidade).annotate(
                month=ExtractMonth('data'),
                year=ExtractYear('data')) \
                .values('month', 'year') \
                .annotate(total=Count('id'))
            atendimentos_por_especialidade.append({'especialidade': especialidade, 'atendimentos': atendimentos})

        return atendimentos_por_especialidade


class RelatPdfAtendimentoEspecialidadeListView(View):

    def get(self, request):
        atendimento_por_especialidade = AtendimentoEspecialidadeListView().get_queryset()
        print(atendimento_por_especialidade)
        html_string = render_to_string('relatorios/pdfatendimento_por_especialidade.html',
                                       {'atendimento_por_especialidade': atendimento_por_especialidade})

        result = BytesIO()

        pdf = pisa.pisaDocument(BytesIO(html_string.encode("UTF-8")), result)

        if not pdf.err:
            response = HttpResponse(result.getvalue(), content_type='application/pdf')
            return response

        return HttpResponse('Erro ao gerar PDF: %s' % pdf.err)

core/templates/relatorios/atendimento_por_especialidade.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relatórios Atendimentos por Especialidade</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" />
</head>

<body>
    <h1>Relatórios Atendimentos por Especialidade</h1>
    <table>
        <thead>
            <tr>
                <th>Especialidade</th>
                <th>Mês</th>
                <th>Ano</th>
                <th>Quantidade de Pacientes</th>
            </tr>
        </thead>
        <tbody>
            {% for item in atendimento_por_especialidade %}
                {% for atendimento in item.atendimentos %}
                    <tr>
                        <td>{{ item.especialidade }}</td>
                        <td>{{ atendimento.month }}</td>
                        <td>{{ atendimento.year }}</td>
                        <td>{{ atendimento.total }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    <table>
        <p>
            <a href="{% url 'pdfatendimento_por_especialidade' %}" role="button">Gerar PDF</a>
        </p>
    </table>
</body>

</html>

core/templates/relatorios/consulta_por_especialidade.html
{% extends 'base.html' %}

{% block titulo %}Minha Clínica 2024 - Relatório de Consultas por Especialidade{% endblock %}

{% block conteudo %}
<article>
    <h1>Relatório de Consultas por Especialidade</h1>
    <table class="striped">
        <thead>
            <tr>
                <th>Paciente</th>
                <th>Médico</th>
                <th>Data</th>
                <th>Horário</th>
            </tr>
        </thead>
        <tbody>
            {% for consulta in consultas %}
            <tr>
                <td>{{ consulta.paciente.nome }}</td>
                <td>{{ consulta.medico.nome }}</td>
                <td>{{ consulta.data }}</td>
                <td>{{ consulta.horario }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">Não existem consultas cadastradas para esta especialidade</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>
        <a href="{% url 'pdfconsulta_por_especialidade' %}?especialidade={{ especialidade }}" role="button" target="_blank">
            Gerar PDF
        </a>
    </p>
</article>
{% endblock %}

core/templates/relatorios/pacientes.html
{% extends 'base.html' %}

{% block titulo %}Minha Clínica 2024 - Relatório Pacientes {% endblock %}
{% block conteudo %}
        <article>
            <h1>Relatório de Pacientes</h1>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Cidade</th>
                        <th>Idade</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in pacientes %}
                    <tr>
                        <td>{{ p.nome }}</td>
                        <td>{{ p.telefone }}</td>
                        <td>{{ p.cidade }}</td>
                        <td>{{ p.idade }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Não existem pacientes cadastrados</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p>
                <a href="{% url 'pdf_pacientes' %}" role="button" target="_blank">
                    Gerar PDF
                </a>
            </p>
        </article>
{% endblock %}

core/templates/relatorios/pacientes_por_convenio.html
{% extends 'base.html' %}

{% block titulo %}Minha Clínica 2024 - Pacientes por Convênio{% endblock %}

{% block conteudo %}
<article>
    <h1>Relatório de Pacientes por Convênio</h1>
    {% if convenio %}
        <h2>{{ convenio.nome }}</h2>
        <table class="striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Idade</th>
                </tr>
            </thead>
            <tbody>
                {% for paciente in convenio.paciente_set.all %}
                    <tr>
                        <td>{{ paciente.nome }}</td>
                        <td>{{ paciente.idade }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">Não existem pacientes cadastrados para este convênio</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Não há convênios cadastrados.</p>
    {% endif %}
    <p>
        <a href="{% url 'RelatPdfPacientesPorConvenio' %}" role="button" target="_blank">
            Gerar PDF
        </a>
    </p>
</article>
{% endblock %}

core/templates/relatorios/pdfatendimento_por_especialidade.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relatórios Atendimentos por Especialidade</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css" />
</head>

<body>
    <h1>Relatórios Atendimentos por Especialidade</h1>
    <table>
        <thead>
            <tr>
                <th>Especialidade</th>
                <th>Mês</th>
                <th>Ano</th>
                <th>Quantidade de Pacientes</th>
            </tr>
        </thead>
        <tbody>
            {% for item in atendimento_por_especialidade %}
                {% for atendimento in item.atendimentos %}
                    <tr>
                        <td>{{ item.especialidade }}</td>
                        <td>{{ atendimento.month }}</td>
                        <td>{{ atendimento.year }}</td>
                        <td>{{ atendimento.total }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    <table>
        <p>
            <a href="{% url 'pdfatendimento_por_especialidade' %}" role="button">Gerar PDF</a>
        </p>
    </table>
</body>

</html>

core/templates/relatorios/pdfconsulta_por_especialidade.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Relatório de Consultas</title>
    <style>
        h1 {
            text-align: center;
            font-size: 2rem;
            color: darkgreen;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: lightgrey;
        }
    </style>
</head>
<body>
    <main class="container">
        <article>
            <h1>Relatório de Consultas</h1>
            <table>
                <thead>
                    <tr>
                        <th>Paciente</th>
                        <th>Médico</th>
                        <th>Data</th>
                        <th>Horário</th>
                    </tr>
                </thead>
                <tbody>
                    {% for consulta in consultas %}
                    <tr>
                        <td>{{ consulta.paciente.nome }}</td>
                        <td>{{ consulta.medico.nome }}</td>
                        <td>{{ consulta.data }}</td>
                        <td>{{ consulta.horario }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Não existem consultas cadastradas</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </article>
    </main>
</body>
</html>

core/templates/relatorios/pdfpacientes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Relatório Pacientes</title>
    <style>
        h1{
            text-align:center;
            font-size: 2rem;
            color: darkgreen;
        }
        tr, td, th{
            border: 1px solid black;
            border-colapse: colapse;
            padding: 0.5em;
        }

        th{
            text-align: left;
			background-color: lightgrey;
        }
    </style>
</head>
<body>
    <main class="container">
        <article>
            <h1>Relatório de Pacientes</h1>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Cidade</th>
                        <th>Idade</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in pacientes %}
                    <tr>
                        <td>{{ p.nome }}</td>
                        <td>{{ p.telefone }}</td>
                        <td>{{ p.cidade }}</td>
                        <td>{{ p.idade }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Não existem pacientes cadastrados</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </article>
    </main>
</body>
</html>

core/templates/relatorios/pdfpacientes_por_convenio.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Relatório Pacientes por Convênio</title>
    <style>
        h1 {
            text-align: center;
            font-size: 2rem;
            color: darkgreen;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: lightgrey;
        }
    </style>
</head>
<body>
    <main class="container">
        <article>
            <h1>Relatório de Pacientes por Convênio</h1>
            {% for convenio, pacientes in convenios.items %}
            <h2>{{ convenio }}</h2>
            <table>
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Cidade</th>
                        <th>Idade</th>
                    </tr>
                </thead>
                <tbody>
                    {% for paciente in pacientes %}
                    <tr>
                        <td>{{ paciente.nome }}</td>
                        <td>{{ paciente.telefone }}</td>
                        <td>{{ paciente.cidade }}</td>
                        <td>{{ paciente.idade }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4">Não existem pacientes cadastrados para este convênio</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% empty %}
            <p>Não há convênios cadastrados.</p>
            {% endfor %}
        </article>
    </main>
</body>
</html>